name: Build Kivy App for Android

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git python3-pip openjdk-8-jdk unzip zlib1g-dev
        sudo pip3 install --upgrade cython
        sudo pip3 install buildozer

    - name: Accept Android SDK licenses
      run: |
        yes | sdkmanager --licenses
        sdkmanager "build-tools;36.0.0-rc4"

    - name: Build the APK
      run: |
        buildozer init
        buildozer android debug

    - name: Archive release APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: bin/*.apk

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download release APK
      uses: actions/download-artifact@v4
      with:
        name: release-apk

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: bin/*.apk
        asset_name: app-release.apk
        asset_content_type: application/vnd.android.package-archive
