name: Build macOS App

on:
  push:
    branches:
      - main  # Se ejecutará en cada push a la rama main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller==5.13.2 # Última versión estable compatible

      - name: Compilar con PyInstaller
        run: |
          pyinstaller --onefile --windowed protocolos_medicos_visual_kivy.py  # Generará el ejecutable en dist/

      - name: Subir ejecutable como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: kivy-macOS-build
          path: dist/protocolos_medicos_visual_kivy  # PyInstaller genera un archivo sin extensión en macOS

      - name: Crear Release y Subir Ejecutable
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0  # O hazlo dinámico si quieres cambiar en cada versión
          release_name: "Release v1.0.0"
          draft: false
          prerelease: false
          files: dist/protocolos_medicos_visual_kivy  # Ruta corregida
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
