name: Build macOS App

on:
  push:
    branches:
      - main  # Cambia si usas otra rama principal
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Compilar con PyInstaller
        run: |
          pyinstaller --onefile --windowed main.py  # Ajusta el nombre de tu archivo principal

      - name: Subir ejecutable como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: kivy-macOS-build
          path: dist/main  # Cambia 'main' si el binario tiene otro nombre
